export const translations = {
  hi: {
    home: 'होम',
    categories: 'श्रेणियां',
    search: 'खोजें',
    contact: 'संपर्क',
    readMore: 'और पढ़ें',
    trending: 'ट्रेंडिंग न्यूज',
    latest: 'ताज़ा खबरें',
    featured: 'मुख्य समाचार',
    aboutUs: 'हमारे बारे में',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम और शर्तें',
    newsletter: 'न्यूज़लेटर सब्सक्राइब करें',
    shareArticle: 'लेख साझा करें',
    breakingNews: 'ब्रेकिंग न्यूज',
    topStories: 'मुख्य समाचार',
    moreNews: 'अन्य समाचार',
    popular: 'लोकप्रिय',
    advertisement: 'विज्ञापन',
    news: 'समाचार',
    tech: 'तकनीक',
    ai: 'कृत्रिम बुद्धिमत्ता',
    tips: 'टिप्स',
    reviews: 'समीक्षाएं',
    astrology: 'ज्योतिष',
    numerology: 'अंकज्योतिष',
    dreams: 'सपने',
    angelNumbers: 'एंजेल नंबर',
    blogging: 'ब्लॉगिंग',
    earnOnline: 'ऑनलाइन कमाई',

    // Additional Categories
    'tech-ai': 'तकनीक और एआई',
    'dreams-numerology': 'सपने और अंकज्योतिष',
    'app-reviews': 'ऐप समीक्षाएं',
    'cricket-sports': 'क्रिकेट और खेल',
    'lifestyle-trends': 'जीवनशैली और ट्रेंड्स',
    'market-manufacturing': 'बाज़ार और निर्माण',
  },
  en: {
    home: 'Home',
    categories: 'Categories',
    search: 'Search',
    contact: 'Contact',
    readMore: 'Read More',
    trending: 'Trending News',
    latest: 'Latest News',
    featured: 'Top Stories',
    aboutUs: 'About Us',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    newsletter: 'Subscribe to Newsletter',
    shareArticle: 'Share Article',
    breakingNews: 'Breaking News',
    topStories: 'Top Stories',
    moreNews: 'More News',
    popular: 'Popular',
    advertisement: 'Advertisement',
    news: 'News',
    tech: 'Tech',
    ai: 'AI',
    tips: 'Tips',
    reviews: 'Reviews',
    astrology: 'Astrology',
    numerology: 'Numerology',
    dreams: 'Dreams',
    angelNumbers: 'Angel Numbers',
    blogging: 'Blogging',
    earnOnline: 'Earn Online',

    // Additional Categories
    'tech-ai': 'Tech & AI',
    'dreams-numerology': 'Dreams & Numerology',
    'app-reviews': 'App Reviews',
    'cricket-sports': 'Cricket & Sports',
    'lifestyle-trends': 'Lifestyle & Trends',
    'market-manufacturing': 'Market & Manufacturing',
  },
  mr: {
    home: 'होम',
    categories: 'श्रेणी',
    search: 'शोध',
    contact: 'संपर्क',
    readMore: 'अधिक वाचा',
    trending: 'ट्रेंडिंग न्यूज',
    latest: 'ताज्या बातम्या',
    featured: 'मुख्य बातम्या',
    aboutUs: 'आमच्याबद्दल',
    privacyPolicy: 'गोपनीयता धोरण',
    termsConditions: 'अटी आणि शर्ती',
    newsletter: 'न्यूजलेटर सब्सक्राइब करा',
    shareArticle: 'लेख शेअर करा',
    breakingNews: 'ब्रेकिंग न्यूज',
    topStories: 'मुख्य बातम्या',
    moreNews: 'इतर बातम्या',
    popular: 'लोकप्रिय',
    advertisement: 'जाहिरात',
    news: 'बातम्या',
    tech: 'तंत्रज्ञान',
    ai: 'एआय',
    tips: 'टीप्स',
    reviews: 'पुनरावलोकने',
    astrology: 'ज्योतिष',
    numerology: 'अंकज्योतिष',
    dreams: 'स्वप्ने',
    angelNumbers: 'देवदूत क्रमांक',
    blogging: 'ब्लॉगिंग',
    earnOnline: 'ऑनलाइन कमाई',

    // Additional Categories
    'tech-ai': 'तंत्रज्ञान आणि एआय',
    'dreams-numerology': 'स्वप्ने आणि अंकज्योतिष',
    'app-reviews': 'अ‍ॅप पुनरावलोकने',
    'cricket-sports': 'क्रिकेट आणि खेळ',
    'lifestyle-trends': 'जीवनशैली आणि ट्रेंड्स',
    'market-manufacturing': 'बाजार आणि उत्पादन',
  },
  ta: {
    home: 'முகப்பு',
    categories: 'வகைகள்',
    search: 'தேடு',
    contact: 'தொடர்பு',
    readMore: 'மேலும் படிக்க',
    trending: 'டிரென்டிங் செய்திகள்',
    latest: 'சமீபத்திய செய்திகள்',
    featured: 'முக்கிய செய்திகள்',
    aboutUs: 'எங்களை பற்றி',
    privacyPolicy: 'தனியுரிமை கொள்கை',
    termsConditions: 'விதிமுறைகள்',
    newsletter: 'செய்திமடல் சந்தா',
    shareArticle: 'கட்டுரை பகிர்',
    breakingNews: 'அவசர செய்தி',
    topStories: 'முக்கிய செய்திகள்',
    moreNews: 'மேலும் செய்திகள்',
    popular: 'பிரபலமான',
    advertisement: 'விளம்பரம்',
    news: 'செய்திகள்',
    tech: 'தொழில்நுட்பம்',
    ai: 'ஏஐ',
    tips: 'குறிப்புகள்',
    reviews: 'விமர்சனங்கள்',
    astrology: 'ஜோதிடம்',
    numerology: 'எண்கள்',
    dreams: 'கனவுகள்',
    angelNumbers: 'தேவதூதர் எண்கள்',
    blogging: 'வலைப்பதிவு',
    earnOnline: 'நிகழ்நேர வருமானம்',

    // Additional Categories
    'tech-ai': 'தொழில்நுட்பம் & ஏஐ',
    'dreams-numerology': 'கனவுகள் மற்றும் எண்கள்',
    'app-reviews': 'அப்பிளிக்கேஷன் விமர்சனங்கள்',
    'cricket-sports': 'கிரிக்கெட் & விளையாட்டுகள்',
    'lifestyle-trends': 'வாழ்க்கை முறை & போக்குகள்',
    'market-manufacturing': 'சந்தை & உற்பத்தி',
  },
  te: {
    home: 'హోమ్',
    categories: 'వర్గాలు',
    search: 'వెతుకు',
    contact: 'సంప్రదింపు',
    readMore: 'మరింత చదవండి',
    trending: 'ట్రెండింగ్ న్యూస్',
    latest: 'తాజా వార్తలు',
    featured: 'ముఖ్య వార్తలు',
    aboutUs: 'మా గురించి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsConditions: 'నిబంధనలు',
    newsletter: 'న్యూస్‌లెటర్ సబ్‌స్క్రైబ్',
    shareArticle: 'వ్యాసం షేర్ చేయండి',
    breakingNews: 'బ్రేకింగ్ న్యూస్',
    topStories: 'ముఖ్య వార్తలు',
    moreNews: 'మరిన్ని వార్తలు',
    popular: 'ప్రసిద్ధ',
    advertisement: 'ప్రకటన',
    news: 'వార్తలు',
    tech: 'టెక్నాలజీ',
    ai: 'ఏఐ',
    tips: 'సూచనలు',
    reviews: 'సమీక్షలు',
    astrology: 'జ్యోతిష్యం',
    numerology: 'సంఖ్యాశాస్త్రం',
    dreams: 'కలలు',
    angelNumbers: 'దూత సంఖ్యలు',
    blogging: 'బ్లాగింగ్',
    earnOnline: 'ఆన్‌లైన్ ఆదాయం',

    // Additional Categories
    'tech-ai': 'టెక్నాలజీ & ఏఐ',
    'dreams-numerology': 'కలలు & సంఖ్యాశాస్త్రం',
    'app-reviews': 'యాప్ సమీక్షలు',
    'cricket-sports': 'క్రికెట్ & క్రీడలు',
    'lifestyle-trends': 'జీవనశైలి & ధోరణులు',
    'market-manufacturing': 'మార్కెట్ & తయారీ',
  },
};
